### ISSUE TITLE
Dope sweet potato

### ISSUE THREAD

**Issue by MIGUEL-LO** [UCL-RITS/rsd-classwork-2019#7]
![image](https://user-images.githubusercontent.com/56116815/66611968-0ca28c80-ebb8-11e9-8555-343d66140492.png)
Answers UCL-RITS/rsd-classwork-2019#1

**Comment by sukrire** [comment]
![image](https://user-images.githubusercontent.com/56116777/67944957-aff22a80-fbd5-11e9-8d43-ec4ba2f34b1c.png)

**Comment by lukelbro** [comment]
![cheesy_potato](https://user-images.githubusercontent.com/53307399/67945139-1a0acf80-fbd6-11e9-9f17-6d9372a7485b.png)

Tastes better with cheese!

**Comment by MIGUEL-LO** [comment]
Vegan cheese?

**Comment by dsinghl** [comment]
<img width="656" alt="Screenshot 2019-10-31 at 12 03 14" src="https://user-images.githubusercontent.com/31862881/67945939-1415ee00-fbd8-11e9-8c89-f87894722c22.png">

**Comment by owainkenwayucl** [comment]
Thanks for the giggle.
